[theme]
base = "dark"
primaryColor = "#22D3EE"
backgroundColor = "#050B14"
secondaryBackgroundColor = "#0E223E"
textColor = "#E6F7FF"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
enableStaticServing = false
maxUploadSize = 1

[client]
showErrorDetails = "none"
toolbarMode = "viewer"

[browser]
gatherUsageStats = false
